// <auto-generated />
namespace Tunr.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class AlphaKeys : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AlphaKeys));
        
        string IMigrationMetadata.Id
        {
            get { return "201406160543504_AlphaKeys"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
