// <auto-generated />
namespace Tunr.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class DoubleBitrate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DoubleBitrate));
        
        string IMigrationMetadata.Id
        {
            get { return "201504182130417_DoubleBitrate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
